gradient_accumulation_steps: 512
mixed_precision: "fp16"
wandb_enabled: true
gradient_checkpointing: true
max_train_steps: 5000
validation_steps: 100
checkpoints_total_limit: 1000
train_batch_size: 12
audio_length_left: 2
audio_length_right: 2